//
// shared/customdefs.qc - Definitions used for both CSQC's client and the server..
//

//==- Client Events -==//
#define EVENT_WEAPONCHANGE      1
#define EVENT_GAMEMODESET       2

//==- Stats -==//
#define STAT_CURRENTMAG         1
#define STAT_AMMO        2

//==- Weapons -==//

#define W_COLT                  1
#define W_STG                   2

//==- Gamemode Stuff -==//
#define GM_TDM                  1

//==- Misc. -==//
float gamemode;